export const hotelTypes = [
    "Boutique",
    "Villa",
    "Apartment",
    "Hotel",
    "Resort",
    "Homestay",
    "GuestHouse",
    "Hostel",
    "Houseboat",
    "Camp",
    "Motel",
    "Inn",
    "Capsule Hotel",
    "Treehouse",
    "Cottage",
];

export const hotelFacilities = [
    "Free Wi-Fi",
    "Parking",
    "Restaurant",
    "Room Service",
    "Swimming Pool",
    "Fitness Center",
    "Spa",
    "Air Conditioning",
    "Bar/Lounge",
    "Business Center",
    "Laundry Service",
    "Wheelchair Accessible",
    "Childcare Services",
    "Currency Exchange",
    "Garden",
    "Luggage Storage",
    "Non-Smoking Rooms",
    "Tea/Coffee Maker in Rooms",
    "Satellite TV",
    "Hair Dryer",
    "Iron/Ironing Board",
    "Beach Access",
    "Bicycle Rental",
    "Gift Shop",
    "Hiking Trails",
    "Library",
    "Nightclub",
];
